### ISSUE TITLE
Keep branch `oop` in sync with master

### ISSUE THREAD

**Issue by moodmosaic** [klimisa/CargoTracker2FSharp#14]
If #13 is merged, we should push `oop` into `master`. Can we automate this via GitHub Actions?

**Comment by klimisa** [comment]
Tell me your opinion on that. I want to keep `oop` branch as the C# to F# migration branch. Create another one for FP, maybe called `fp` where the FP changes will be made and another `ddd` where I will try to bring the codebase a close to the book `Domain Modelling Made Functional`

In the end, `ddd` branch will be in sync with the `master`. 

Any thought?

**Comment by moodmosaic** [comment]
TBH, I'd rather call those branches for now as `phase-0`, `phase-1`, etcetera, and later on I would decide which branch is what; it's just a bit early stage now is all.

---

`fp` can be confusing because with F# there [*will* be](https://eiriktsarpalis.wordpress.com/2017/03/20/why-oo-matters-in-f/) what (Don Syme calls) [object-programming](https://twitter.com/dsymetweets/status/843849405212098560) parts baked in, even in the 'final/functional' version.

**Comment by klimisa** [comment]
Yes you right, let's go for phase-0, phase-1 for now.

**Comment by klimisa** [comment]
I created `phase-0` for the work until now, and `phase-1` for the current work.

**Comment by moodmosaic** [comment]
Sounds good. I created https://github.com/klimisa/CargoTracker2FSharp/pull/17 just in case you want to wipe out `oop` branch.
